[package]
name = "instancing"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]
build = "build.rs"

[dependencies]
embree = { path = "../../" }
support = { path = "../support" }
cgmath = "0.16.1"

