[package]
name = "support"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]

[dependencies]
image = "0.22.0"
arcball = {path = "../../../arcball" }
cgmath = "0.18.0"
clock_ticks = "0.1.1"

[dependencies.glium]
version = "0.25.0"
default = ["glutin"]

