[package]
name = "support"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]

[dependencies]
glium = "0.20.0"
image = "0.18.0"
arcball = "0.3.1"
cgmath = "0.16.1"
clock_ticks = "0.1.1"

