[package]
name = "support"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]

[dependencies]
image = "0.22.0"
arcball = "1.0.0"
cgmath = "0.17.0"
clock_ticks = "0.1.1"

[dependencies.glium]
version = "0.25.0"
default = ["glutin"]

