[package]
name = "support"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]

[dependencies]
glium = "0.17.0"
image = "0.15.0"
arcball = "0.3.0"
cgmath = "0.15.0"
clock_ticks = "0.1.1"

