[package]
name = "support"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]

[dependencies]
glium = "0.21.0"
image = "0.18.0"
arcball = "1.0.0"
cgmath = "0.17.0"
clock_ticks = "0.1.1"

