name: Embree-rs CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - uses: actions-rs/cargo@v1
              with:
                  command: build
            - run: |
              wget https://github.com/embree/embree/releases/download/v${EMBREE_VERSION}/embree-${EMBREE_VERSION}.x86_64.linux.tar.gz;
              tar -xf embree-${EMBREE_VERSION}.x86_64.linux.tar.gz;
              source embree-${EMBREE_VERSION}.x86_64.linux/embree-vars.sh;
              export EMBREE_DIR=`pwd`/embree-${EMBREE_VERSION}.x86_64.linux/;
            - run: cargo build
            - run: cargo test
            - run: cargo doc
            - run: scripts/build-examples-linux-mac.sh
